In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.cluster import KMeans

#Tutorial can be found here: https://www.youtube.com/watch?v=CIfZi0niNE0

In [131]:
dataset = pd.read_csv('CoffeeBeansCleaned.csv')

In [132]:
X = dataset

In [133]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[-14,-13,-12])], remainder="passthrough")

In [134]:
X_train = np.array(ct.fit_transform(X))

In [135]:
#Clustering
km = KMeans(n_clusters = 3, init="k-means++", random_state=42)
y_means = km.fit(X_train)

In [136]:
y_means

KMeans(n_clusters=3, random_state=42)

In [137]:
#Centers
y_means.cluster_centers_

array([[3.80952381e-01, 3.57142857e-01, 2.61904762e-01, 4.04761905e-01,
        5.71428571e-01, 2.38095238e-02, 3.33333333e-01, 2.38095238e-01,
        1.42857143e-01, 1.19047619e-01, 9.52380952e-02, 7.14285714e-02,
        7.16071429e+00, 7.05357143e+00, 6.97023810e+00, 7.07142857e+00,
        6.97023810e+00, 1.00000000e+01, 7.00595238e+00, 1.00000000e+01,
        1.00000000e+01, 7.10714286e+00, 7.93392857e+01],
       [4.48275862e-01, 3.79310345e-01, 1.72413793e-01, 6.89655172e-01,
        2.93103448e-01, 1.72413793e-02, 1.89655172e-01, 1.37931034e-01,
        3.62068966e-01, 1.72413793e-01, 8.62068966e-02, 5.17241379e-02,
        6.81896552e+00, 6.56034483e+00, 6.42672414e+00, 6.38362069e+00,
        6.35344828e+00, 1.00000000e+01, 6.41810345e+00, 1.00000000e+01,
        1.00000000e+01, 6.43534483e+00, 7.53706897e+01],
       [2.68292683e-01, 3.04878049e-01, 4.26829268e-01, 7.07317073e-01,
        2.07317073e-01, 8.53658537e-02, 1.82926829e-01, 7.31707317e-02,
        1.21951220e-01, 1.82926829e-01, 2.19512195e-01, 2.19512195e-01,
        6.37817073e+00, 6.15243902e+00, 6.07926829e+00, 6.06707317e+00,
        6.10670732e+00, 1.00000000e+01, 6.12195122e+00, 1.00000000e+01,
        1.00000000e+01, 6.15548780e+00, 7.29908537e+01]])

In [138]:
#Check where each record resides in which cluster
km.labels_

array([2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 0,
       2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1,
       0, 1, 1, 1, 2, 0, 0, 2, 1, 2, 2, 1, 2, 0, 0, 2, 0, 0, 2, 1, 0, 0,
       2, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1,
       1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2,
       0, 1, 2, 0, 0, 1, 0, 2, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 1,
       2, 2, 2, 2, 2, 2])

In [139]:
#Count how many records are in each of the clusters
labels = km.labels_

clusterCount = np.bincount(labels)
clusterCount

array([42, 58, 82], dtype=int64)

In [145]:
#List the records in dataframe form

df_with_cluster_column = pd.read_csv('CoffeeBeansCleaned.csv')

cluster = km.labels_
df_with_cluster_column['cluster'] = cluster

df_with_cluster_column

,Variety,Shape,Sieve,Aroma,Flavor,Aftertaste,Acidity,Body,Uniformity,Balance,clean cup,Sweetness,Taster score,Final score,cluster
0,CO,PE,13,6.50,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.50,2
1,CO,PE,13,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.00,2
2,CO,PE,13,6.75,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.75,2
3,CO,PE,13,6.75,6.50,6.50,6.00,6.00,10,6.00,10,10,6.00,73.75,2
4,CO,MI,13,6.75,6.25,6.25,6.25,6.50,10,6.50,10,10,6.50,75.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,OA,FL,18,6.50,6.00,6.00,6.00,6.25,10,6.00,10,10,6.00,72.75,2
178,OA,FL,18,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.25,72.25,2
179,OA,FL,18,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.50,72.50,2
180,OA,FL,18,6.25,6.25,6.25,6.00,6.25,10,6.00,10,10,6.25,73.25,2
181,OA,FL,18,6.25,6.25,6.25,6.25,6.25,10,6.25,10,10,6.25,73.75,2

In [177]:
#List the elements of cluster n method
def display(fullList, clusternum):
    new_list = []
    for x in list_with_clusters:
        for y in x:
            if x[14] == clusternum:
                new_list.append(x)
                break
    unique_df = pd.DataFrame(new_list)
    return unique_df

In [178]:
list_with_clusters = df_with_cluster_column.values.tolist()

#List elements of cluster 0
df_n = display(list_with_clusters, 0)
df_n

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,CO,MI,14,7.00,7.00,7.25,7.25,7.00,10,7.00,10,10,7.25,79.75,0
1,CO,MI,14,7.75,7.25,7.25,7.25,7.00,10,7.00,10,10,7.25,80.75,0
2,CO,MI,14,7.50,7.00,7.00,7.00,6.50,10,7.25,10,10,7.25,79.50,0
3,CO,MI,15,7.00,7.00,7.00,6.75,7.00,10,6.75,10,10,6.75,78.25,0
4,CO,MI,15,7.25,7.25,7.00,7.00,6.75,10,7.25,10,10,7.00,79.50,0
5,CO,FL,13,7.00,7.00,7.00,7.25,7.00,10,7.00,10,10,7.00,79.25,0
6,CO,FL,13,7.50,7.25,7.50,7.25,7.25,10,7.25,10,10,7.25,81.25,0
7,CO,FL,13,7.00,7.00,7.00,7.00,6.50,10,7.00,10,10,7.00,78.50,0
8,CO,FL,16,7.00,7.25,7.25,7.25,7.25,10,7.25,10,10,7.50,80.75,0
9,CO,FL,16,7.25,7.25,6.75,7.00,7.00,10,6.50,10,10,6.75,78.50,0
10,CO,FL,16,7.00,6.75,6.25,7.00,6.50,10,6.75,10,10,7.25,77.50,0
11,CO,FL,16,7.50,7.75,7.00,7.00,7.00,10,7.00,10,10,7.00,80.25,0
12,CO,FL,17,7.50,7.25,7.50,7.50,7.00,10,7.25,10,10,7.25,81.25,0
13,CO,FL,17,7.50,7.25,7.25,7.25,7.25,10,7.25,10,10,7.25,81.00,0
14,CO,FL,18,7.00,7.25,7.00,7.75,7.25,10,7.00,10,10,7.25,80.50,0
15,CO,FL,18,7.00,7.00,7.00,7.25,7.00,10,7.00,10,10,7.25,79.50,0
16,CR,MI,13,7.00,7.25,7.25,7.25,7.25,10,7.25,10,10,7.25,80.50,0
17,CR,MI,13,6.75,6.75,6.75,6.75,6.75,10,6.75,10,10,7.00,77.50,0
18,CR,MI,13,7.25,7.50,7.50,7.00,7.00,10,7.25,10,10,7.25,80.75,0
19,CR,MI,13,7.50,7.25,6.25,6.25,6.50,10,7.00,10,10,7.00,77.75,0
20,CR,MI,13,6.50,7.00,7.00,6.75,6.75,10,6.75,10,10,7.00,77.75,0
21,CR,MI,14,7.25,7.00,7.00,7.25,7.25,10,7.00,10,10,7.00,79.75,0
22,CR,MI,14,7.00,7.25,7.25,7.25,7.00,10,7.25,10,10,7.25,80.25,0
23,CR,MI,14,7.00,7.25,7.00,7.25,7.25,10,7.25,10,10,7.50,80.50,0
24,CR,MI,14,7.75,7.00,6.50,6.75,6.50,10,7.00,10,10,7.00,78.50,0
25,CR,MI,14,7.00,7.00,7.25,7.25,7.25,10,7.00,10,10,7.00,79.75,0
26,CR,MI,14,7.00,6.75,6.75,6.50,7.00,10,6.50,10,10,7.00,77.50,0
27,CR,MI,15,7.25,7.00,7.00,7.00,6.50,10,7.00,10,10,7.00,78.75,0
28,CR,MI,15,7.50,7.00,7.00,7.25,7.00,10,7.00,10,10,7.00,79.75,0
29,CR,MI,15,7.25,6.50,6.50,7.00,6.25,10,7.00,10,10,7.00,77.50,0
30,CR,MI,15,7.50,7.00,7.00,7.00,7.00,10,7.00,10,10,7.00,79.50,0
31,OA,PE,13,7.00,7.00,7.00,7.00,7.00,10,7.00,10,10,7.00,79.00,0
32,OA,MI,13,7.00,7.25,6.75,7.25,7.25,10,7.00,10,10,7.50,80.00,0
33,OA,MI,13,7.00,7.00,7.00,7.25,7.00,10,7.00,10,10,7.00,79.25,0
34,OA,MI,13,7.00,6.50,6.50,6.50,7.00,10,7.00,10,10,7.00,77.50,0
35,OA,MI,14,7.00,7.00,7.00,7.25,7.25,10,7.00,10,10,7.25,79.75,0
36,OA,FL,13,7.00,7.00,7.00,7.25,7.25,10,7.00,10,10,7.25,79.75,0
37,OA,FL,13,7.25,6.50,6.50,7.25,7.25,10,6.75,10,10,7.00,78.50,0
38,OA,FL,16,7.00,7.00,7.00,7.00,7.00,10,7.00,10,10,7.00,79.00,0
39,OA,FL,17,7.00,7.00,7.00,7.00,7.00,10,7.00,10,10,7.00,79.00,0
40,OA,FL,17,7.00,7.00,7.00,7.00,7.00,10,7.00,10,10,7.00,79.00,0
41,OA,FL,18,7.25,7.00,7.00,7.00,7.25,10,7.00,10,10,7.00,79.50,0

In [179]:
#List elements of cluster 1
df_nplus1 = display(list_with_clusters, 1)
df_nplus1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,CO,MI,13,6.75,6.25,6.25,6.25,6.50,10,6.50,10,10,6.50,75.00,1
1,CO,MI,13,6.50,6.50,6.25,6.25,6.50,10,6.75,10,10,6.75,75.50,1
2,CO,MI,13,7.50,6.50,6.75,6.50,6.50,10,6.50,10,10,6.50,76.75,1
3,CO,MI,14,6.50,6.25,6.00,6.00,6.50,10,6.50,10,10,6.50,74.25,1
4,CO,MI,14,7.00,6.25,6.00,6.50,6.25,10,6.25,10,10,6.25,74.50,1
5,CO,MI,14,7.00,6.50,6.50,6.50,6.25,10,6.50,10,10,6.25,75.50,1
6,CO,FL,13,6.75,6.75,6.50,6.50,6.50,10,6.75,10,10,6.75,76.50,1
7,CO,FL,13,7.25,6.50,6.50,7.00,6.75,10,6.50,10,10,6.50,77.00,1
8,CO,FL,13,7.25,6.50,6.50,7.00,6.75,10,6.50,10,10,6.50,77.00,1
9,CO,FL,14,6.75,6.75,6.75,6.50,6.50,10,6.50,10,10,6.50,76.25,1
10,CO,FL,14,6.75,6.75,6.75,6.75,6.00,10,6.00,10,10,6.50,75.50,1
11,CO,FL,15,6.50,6.50,6.25,6.25,6.25,10,6.25,10,10,6.25,74.25,1
12,CO,FL,15,6.50,6.50,6.25,6.25,6.25,10,6.25,10,10,6.25,74.25,1
13,CO,FL,15,7.00,7.00,7.00,6.00,6.00,10,6.50,10,10,6.50,75.50,1
14,CO,FL,15,6.50,6.75,6.25,6.25,6.25,10,6.25,10,10,6.50,74.75,1
15,CO,FL,15,6.75,6.50,6.00,6.00,6.50,10,6.50,10,10,6.50,74.75,1
16,CO,FL,15,6.75,6.50,6.25,6.00,6.00,10,6.50,10,10,6.50,74.50,1
17,CO,FL,15,6.75,6.25,6.25,6.75,6.00,10,6.25,10,10,6.50,74.75,1
18,CO,FL,16,7.00,6.75,6.75,6.50,6.25,10,6.50,10,10,6.25,76.00,1
19,CO,FL,16,7.00,6.50,6.25,6.25,6.25,10,6.25,10,10,6.25,74.75,1
20,CO,FL,16,6.50,6.50,6.50,6.25,6.25,10,6.50,10,10,7.00,75.50,1
21,CO,FL,16,6.50,6.50,6.50,6.25,6.25,10,6.50,10,10,6.50,75.00,1
22,CO,FL,16,6.50,6.50,6.50,6.75,6.50,10,6.50,10,10,7.00,76.25,1
23,CO,FL,16,7.50,6.25,6.00,6.00,6.25,10,6.25,10,10,6.25,74.50,1
24,CO,FL,17,7.25,6.75,6.75,6.50,6.25,10,6.50,10,10,6.50,76.50,1
25,CO,FL,18,7.25,6.25,6.00,6.25,6.00,10,6.25,10,10,6.25,74.25,1
26,CR,MI,13,7.25,6.25,6.25,6.00,6.50,10,6.25,10,10,6.25,74.75,1
27,CR,MI,13,6.75,6.50,6.50,6.50,6.25,10,6.50,10,10,6.50,75.50,1
28,CR,MI,14,6.50,7.00,6.50,6.50,6.50,10,6.50,10,10,6.50,76.00,1
29,CR,MI,15,7.00,6.75,6.75,6.50,6.50,10,6.50,10,10,6.00,76.00,1
30,CR,MI,15,7.00,6.25,6.25,6.00,6.25,10,6.25,10,10,6.25,74.25,1
31,CR,MI,15,6.75,6.50,6.50,6.25,6.00,10,6.25,10,10,6.00,74.25,1
32,CR,MI,15,6.75,6.50,6.50,6.25,6.25,10,6.25,10,10,6.25,74.75,1
33,CR,MI,15,6.75,6.50,6.50,7.00,6.50,10,6.50,10,10,6.50,76.25,1
34,CR,FL,15,6.50,6.75,6.50,7.00,6.50,10,6.50,10,10,6.50,76.25,1
35,CR,FL,15,6.50,6.75,6.50,7.00,6.50,10,6.50,10,10,6.50,76.25,1
36,CR,FL,15,6.50,6.50,6.25,6.25,6.50,10,6.50,10,10,6.50,75.00,1
37,CR,FL,15,7.25,7.00,7.00,6.00,6.50,10,6.50,10,10,7.00,77.25,1
38,CR,FL,15,6.75,6.50,6.00,6.25,6.75,10,6.50,10,10,6.50,75.25,1
39,CR,FL,15,6.50,6.50,6.50,6.25,6.50,10,6.50,10,10,6.25,75.00,1
40,CR,FL,15,7.00,6.75,6.50,6.00,7.00,10,6.50,10,10,6.50,76.25,1
41,CR,FL,15,7.25,7.00,6.75,6.00,6.50,10,6.50,10,10,6.50,76.50,1
42,CR,FL,16,6.50,6.25,6.25,6.00,6.25,10,6.50,10,10,6.50,74.25,1
43,CR,FL,16,6.75,6.25,6.25,6.50,6.25,10,6.25,10,10,6.25,74.50,1
44,CR,FL,16,6.75,6.50,6.50,6.75,6.50,10,6.50,10,10,6.50,76.00,1
45,CR,FL,17,6.75,7.00,6.75,6.50,6.50,10,6.50,10,10,7.00,77.00,1
46,CR,FL,17,6.75,6.50,6.25,6.25,6.25,10,6.50,10,10,6.50,75.00,1
47,CR,FL,17,7.00,6.25,6.25,6.25,6.25,10,6.25,10,10,6.25,74.50,1
48,OA,PE,13,7.00,6.50,6.50,6.50,6.00,10,6.00,10,10,6.00,74.50,1
49,OA,MI,13,7.00,6.75,6.75,6.50,6.25,10,6.25,10,10,6.25,75.75,1
50,OA,MI,14,6.75,7.00,6.50,6.50,6.25,10,6.00,10,10,6.00,75.00,1
51,OA,MI,15,6.75,6.25,6.25,6.25,6.25,10,7.00,10,10,6.00,74.75,1
52,OA,FL,13,6.50,6.50,6.50,6.50,6.25,10,6.50,10,10,6.50,75.25,1
53,OA,FL,14,6.50,6.75,6.25,6.50,6.75,10,6.50,10,10,6.50,74.75,1
54,OA,FL,16,7.00,6.50,6.50,6.25,6.25,10,6.25,10,10,6.50,75.25,1
55,OA,FL,17,7.00,6.75,6.50,6.50,6.25,10,6.50,10,10,6.50,76.00,1
56,OA,FL,18,6.25,6.50,6.25,6.50,6.25,10,6.25,10,10,6.50,74.50,1
57,OA,FL,18,7.00,6.75,6.50,6.25,6.25,10,6.50,10,10,6.50,75.75,1

In [180]:
#List elements of cluster 2
df_nplus2 = display(list_with_clusters, 2)
df_nplus2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,CO,PE,13,6.50,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.50,2
1,CO,PE,13,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.00,2
2,CO,PE,13,6.75,6.00,6.00,6.00,6.00,10,6.00,10,10,6.00,72.75,2
3,CO,PE,13,6.75,6.50,6.50,6.00,6.00,10,6.00,10,10,6.00,73.75,2
4,CO,MI,13,6.00,7.00,6.25,6.00,6.00,10,6.25,10,10,6.25,73.75,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,OA,FL,18,6.50,6.00,6.00,6.00,6.25,10,6.00,10,10,6.00,72.75,2
78,OA,FL,18,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.25,72.25,2
79,OA,FL,18,6.00,6.00,6.00,6.00,6.00,10,6.00,10,10,6.50,72.50,2
80,OA,FL,18,6.25,6.25,6.25,6.00,6.25,10,6.00,10,10,6.25,73.25,2
81,OA,FL,18,6.25,6.25,6.25,6.25,6.25,10,6.25,10,10,6.25,73.75,2